### PR TITLE
font_variant_position

### PR DESCRIPTION
**Pull request by NamsooCho**
Sorry.
I'm late.
screen 2016-10-10 10 14 25
screen 2016-10-12 1 29 10

### CODE REVIEW

**Comment by Manishearth** [comment]
Please add `NS_FONT_VARIANT_*` to https://github.com/NamsooCho/stylo-flat/blob/bb25cb13eb2a8adf1eb412aa48f6987e8339f307/servo/components/style/binding_tools/regen.py

Also, could you make a pull request to https://github.com/servo/servo with these changes? You can use `git format-patch --relative=servo @^ servo` to create a patch which can be copied over (and applied with `git am /path/to/patch`). If you don't want to, that's okay too, let me know and I'll copy it over.

Thanks!

**Comment by Manishearth** [comment]
Aside from that, this looks good! Thanks!

**Comment by NamsooCho** [comment]
Yes.
I will try to do that.
Thanks!
1. 10. 12. 오후 8:08에 "Manish Goregaokar" notifications@github.com님이 작성:

**Comment by ghost** [comment]
On a sidenote, we won't be needing the constants. We've already imported all `NS_FONT_*` constants, and opening a PR with these changes will result in conflict. Can you filter only the changes related to `font.mako.rs`?

**Comment by NamsooCho** [comment]
Yes.
I will remove the constants.
Thanks.
1. 10. 12. 오후 8:25에 "Ravi Shankar" notifications@github.com님이 작성:

**Comment by NamsooCho** [comment]
Oh!
This email was not sent to me.
I will just do the requests from you.
1. 10. 12. 오후 8:25에 "Ravi Shankar" notifications@github.com님이 작성:

**Comment by Manishearth** [comment]
I'm sorry, the regen change isn't necessary anymore due to what @Wafflespeanut said.

Just make the change from the first commit (without the constants) on the servo repo and make a pull request there, thanks. It should pass `./mach build-geckolib`. We'll merge there.

**Comment by NamsooCho** [comment]
Ok.
1. 10. 12. 오후 10:51에 "Manish Goregaokar" notifications@github.com님이 작성:

**Comment by Manishearth** [comment]
No need to push here. Are you making the pull request to https://github.com/servo/servo, or do you want me to do it for you?

**Comment by NamsooCho** [comment]
I'm sorry.
I'm confusing servo/servo and stylo-flat.
I'll make pull request to servo/servo without constants.

2016-10-12 22:57 GMT+09:00 Manish Goregaokar notifications@github.com:

**Comment by NamsooCho** [comment]
Help me, please.
I folked servo/servo.
I edited font.mako.rs.
But, ./mach build-geckolib have not been passed.
When I issued the command, the terminal hanged (print nothing on terminal
for over 10 minutes).

2016-10-12 22:51 GMT+09:00 Manish Goregaokar notifications@github.com:

**Comment by Manishearth** [comment]
Make a pull request and I'll try it out locally.

**Comment by Manishearth** [comment]
merged on the servo side

**Pull request closed without merging**
